### ISSUE TITLE
PA Review - Comments/Posting on each others' walls

### ISSUE THREAD

**Issue by trwong** [trwong/fakebook#6]
- [x] Backend: DB, model, controller, views
- [x] Redux loop: ajax, actions, reducers
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by ajansel** [comment]
Great job! This is awesome! A few small things: 
- After hitting enter and submitting the comment, the state should clear 
- The user should be able to edit / delete the comments they make as well

**Comment by trwong** [comment]
I've created tickets and resolved both issues.
